version: "3.9"
services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    depends_on:
      - redis
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
